## help:   ## show this help.
  ##  @fgrep -h "##" $(MAKEFILE_LIST) | fgrep -v fgrep | sed -e 's/\\$$//' | sed -e 's/##//'
catalogue:  ## install catalogue project for roboshop project
    @sh components/catalouge.sh

cart:   ## install cart project for roboshop project
    @sh components/catalouge.sh

